export const userConstants = {
    GET_ALL_USER_REQUEST: 'GET_ALL_USER_REQUEST',
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAILURE: 'GET_ALL_USER_FAILURE',
    GET_SELECTED_USER_REQUEST: 'GET_SELECTED_USER_REQUEST',
    GET_SELECTED_USER_SUCCESS: 'GET_SELECTED_USER_SUCCESS',
    DELETE_CHECKED_USER_REQUEST:'DELETE_CHECKED_USER_REQUEST',
    DELETE_CHECKED_USER_SUCCESS: 'DELETE_CHECKED_USER_SUCCESS',
    DELETE_CHECKED_USER_FAILURE: 'DELETE_CHECKED_USER_FAILURE'
}